car_sharing/car_sharing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
]

car_sharing/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

car_sharing/main/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name='main'

urlpatterns=[
    path('admin/', admin.site.urls),
    # 웹사이트의 첫화면은 index 페이지이다 + URL이름은 index이다
    path('', index, name='index'),
    # URL:80/blog에 접속하면 blog 페이지 + URL이름은 blog이다
    path('board/', board, name='blog'),
    # URL:80/blog/숫자로 접속하면 게시글-세부페이지(posting)
    path('board/<int:pk>', posting, name="posting"),
    # 글쓰기 페이지
    path('board/writing', new_post),
    # 삭제 페이지
    path('board/<int:pk>/remove/', remove_post),
]

car_sharing/common/models.py
from django.db import models

# Create your models here.

car_sharing/main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
# 게시글(Post)엔 제목(postname), 내용(contents)이 존재합니다
class Post(models.Model):
    postname = models.CharField(max_length=50)
    contents = models.TextField()
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    postdate = models.DateTimeField(default=timezone.now())

    # 게시글의 제목(postname)이 Post object 대신하기
    def __str__(self):
        return self.postname

car_sharing/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

car_sharing/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm



def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

car_sharing/main/views.py
from django.shortcuts import render
from django.utils import timezone
from django.core.paginator import Paginator

# View에 Model(Post 게시글) 가져오기
from .models import Post

from django.shortcuts import redirect

# Create your views here.
def index(request):
    return render(request,'main/index.html')

def board(request):
    all_boards = Post.objects.all().order_by("-postdate") # 모든 데이터 조회, 내림차순(-표시) 조회
    paginator = Paginator(all_boards, 5)
    page = int(request.GET.get('page', 1))
    board_list = paginator.get_page(page)
    return render(request, 'main/board.html', {'title':'Board List', 'board_list':board_list})
    '''
    # 모든 Post를 가져와 postlist에 저장합니다
    postlist = Post.objects.all()
    # blog.html 페이지를 열 때, 모든 Post인 postlist도 같이 가져옵니다
    return render(request, 'main/board.html', {'postlist': postlist})'''

# blog의 게시글(posting)을 부르는 posting 함수
def posting(request, pk):
    # 게시글(Post) 중 pk(primary_key)를 이용해 하나의 게시글(post)를 검색
    post = Post.objects.get(pk=pk)
    # posting.html 페이지를 열 때, 찾아낸 게시글(post)을 post라는 이름으로 가져옴
    return render(request, 'main/posting.html', {'post':post})

def new_post(request):
    if request.method == 'POST':
        new_article=Post.objects.create(
            postname=request.POST['postname'],
            contents=request.POST['contents'],
            user=request.user,
            )
        return redirect('./')
    return render(request, 'main/writing.html')


def remove_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('/board')
    return render(request, 'main/remove_post.html', {'Post': post})

car_sharing/common/templates/common/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

car_sharing/common/templates/common/login.html
<!DOCTYPE html>
<html>
<head>
    <title>외대카풀</title>
    <link rel="stylesheet" type="text/css" href="foundation.min.css">
    <link rel="stylesheet" type="text/css" href="login.css">
    <style>
        /* 추가한 스타일 */
        body {
            background-color: #041C3A; 
            color: #D6B534;
            
        }

        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 20px;
            border: 2px solid #D6B534;
            background-color: #041C3A; 
            border-radius: 4px;
        }

        h2 {
            text-align: center;
        }

        .form-group {
            margin-bottom: 20px;
            margin-right: 20px;
        }

        label {
            display: block;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            margin-top: 5px;
            color: #D6B534;
            background-color: #041C3A;
            height: auto;
            border-style: solid;
            border-width: 2px;
            border-color: #D6B534;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 10px;
            border-radius: 10px 10px;
        }

        button:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            box-shadow: 0px 0px 10px #D6B534, 0 0 10px #D6B534, 0px 0px 10px #D6B534;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>로그인</h2>
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include "common/form_errors.html" %}
            <div class="form-group">
                <label for="username">아이디</label>
                <input type="text" id="username" name="username" required value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password">비밀번호</label>
                <input type="password" id="password" name="password" required  value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit">로그인</button>
        </form>
    </div>
</body>
</html>

car_sharing/common/templates/common/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>외대카풀</title>
    <link rel="stylesheet" type="text/css" href="foundation.min.css">
    <link rel="stylesheet" type="text/css" href="login.css">
    <style>
        /* 추가한 스타일 */
        body {
            background-color: #041C3A;
            color: #D6B534;
        }

        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 20px;
            border: 2px solid #D6B534;
            background-color: #041C3A; 
            border-radius: 4px;
        }

        h2 {
            text-align: center;
        }

        .form-group {
            margin-bottom: 20px;
            margin-right: 20px;
        }

        label {
            display: block;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            margin-top: 5px;
            color: #D6B534;
            background-color: #041C3A;
            height: auto;
            border-style: solid;
            border-width: 2px;
            border-color: #D6B534;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 10px;
            border-radius: 10px 10px;
        }

        button:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            box-shadow: 0px 0px 10px #D6B534, 0 0 10px #D6B534, 0px 0px 10px #D6B534;
        }
    </style>

</head>
<body>
    <div class="login-container">
        <h2>회원가입</h2>
        <form method="post" action="{% url 'common:signup' %}">
            {% csrf_token %}
            {% include "common/form_errors.html" %}
            <div class="form-group">
                <label for="username">아이디</label>
                <input type="text" id="username" name="username" value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" id="password" name="password1" value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" id="password" name="password2" value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="text" id="username" name="email" value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <button type="submit">가입하기</button>
        </form>
    </div>
</body>
</html>

car_sharing/common/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>외대카풀</title>
    <link rel="stylesheet" type="text/css" href="foundation.min.css">
    <link rel="stylesheet" type="text/css" href="login.css">
    <style>
        /* 추가한 스타일 */
        body {
            background-color: #E4F5D4; /* 초록색 배경색상 */
        }

        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 20px;
            border: 1px solid #ccc;
            background-color: #F0F5E6; /* 초록색 배경색상 */
        }

        h2 {
            text-align: center;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>로그인</h2>
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="username">아이디</label>
                <input type="text" id="username" name="username" required value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password">비밀번호</label>
                <input type="password" id="password" name="password" required  value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit">로그인</button>
        </form>
    </div>
</body>
</html>

car_sharing/main/templates/main/board.html
<!DOCTYPE html>
<html>

<head>
    <title>HUFS Sharing List</title>
    <style>
        /* 추가한 스타일 */
        body {
            background-color: #041C3A;
            text-align: center;
        }

        .board-container {
            max-width: 800px;
            margin: 50px auto;
            padding: 30px;
            background-color: #D6B534;
            border-radius: 20px 20px;
            height: 450px;
            overflow: auto;
        }

        .category-list {
            list-style: none;
            margin-bottom: 20px;
            text-align: left;
        }

        button {
            margin-top: 5px;
            color: #041C3A;
            background-color: #D6B534;
            height: auto;
            border-style: solid;
            border-width: 4px;
            border-color: #041C3A;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 10px;
            border-radius: 10px 10px;
        }

        button:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            box-shadow: 0px 0px 10px #041C3A, 0 0 10px #041C3A, 0px 0px 10px #041C3A;
        }

        .pl {
            text-decoration: none;
            font-weight: bold;
            font-size: 17px;
            color: #041C3A;
        }
        hr{
            margin-right:50px;
            border: none;
            background-color: #041C3A;
            height:2px;
        }
        .pagination {
            display: flex;           
        }

        .current {
            font-weight: bold;
        }

        a {
            text-decoration: none;
            text-align: center;
        }

        .abutton {
            background-color: #041C3A;
            color: #D6B534;
            font-size: small;
        }

    </style>
</head>

<body>
    <h1 style="margin-top: 50px; font-style: italic;color: #D6B534;
   text-shadow: 0px 0px 20px #D6B534, 0 0 20px #D6B534, 0px 0px 20px #D6B534; font-size:40px;">Sharing List</h1>
    <div class="board-container">
        {% for list in board_list %}
        <ul class="category-list">
            <li><a class="pl" href="{{list.pk}}">{{list.postname}}</a></li>
            <hr>
        </ul>
        {% endfor %}

        <!-- Pagination -->
        <div style="text-align:center;margin-bottom: 20px;">
            <div class="pagination">
            
                <div style="width:35%; margin: 5px;">
                {% if board_list.has_previous %}
                    <a class="abutton" href="?page=1">맨 앞으로</a>
                    <a class="abutton" href="?page={{ board_list.previous_page_number }}">이전</a>
                {% endif %}
                </div>

                <div style="width:30%; margin: 5px;">
                {% for page in board_list.paginator.page_range %}
                    {% if page >= board_list.number|add:-2 and page <= board_list.number|add:2 %}
                    <span class="{% if page == board_list.number %}current{% endif %}">
                        <a href="?page={{ page }}">{{ page}}</a>
                    </span>
                    {% elif page >= board_list.number|add:-3 and page <= board_list.number|add:3 %}
                        ..
                    {% endif %}
                {% endfor %}
                </div>

                <div style="width:35%; margin: 5px;">
                {% if board_list.has_next %}
                    <a class="abutton" href="?page={{ board_list.next_page_number }}">다음</a>
                    <a class="abutton" href="?page={{ board_list.paginator.num_pages }}">맨 뒤로</a>
                {% endif %}
                </div>

            </div>  
        </div> 
        <button><a href="./writing" style="text-decoration: none; color: #041C3A;">Uploading New Post</a></button>
    </div>
    
</body>

</html>

car_sharing/main/templates/main/index.html
<!DOCTYPE html>
<html>

<head>
    <title>HUFS Car Sharing</title>
    <style>
        body {
            background-color: #041C3A;
            font-style: italic;
            text-align: center;
            color: #D6B534;
        }
        
        #funcBox {
            margin: auto;
            max-width: 500px;
            padding: 20px;
            border-style:solid;
            border-radius: 20px 20px;
        }

        .funcList {
            color: #D6B534;
            margin: 30px;
            font-size: 20px;
            
        }

        a {
            text-decoration: none;
            color: #D6B534;

        }
        
        .funcList:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            text-shadow: 0px 0px 10px #D6B534, 0 0 10px #D6B534, 0px 0px 10px #D6B534;
        }
        
        a:visited {
            color: #D6B534;
        }

    </style>
</head>

<body>
    <h1 style="font-size: 50px; color:#D6B534; margin-top:70px; margin-bottom:80px;text-shadow: 0px 0px 50px #D6B534, 0 0 50px #D6B534, 0px 0px 50px #D6B534;">HUFS <br> <strong style="font-size: 80px;">Car Sharing</strong></h1>
    <div id="funcBox">
        {% if  not user.is_authenticated %}
        <div class="funcList">
            <a href="{% url 'common:login' %}">LOGIN</a>
        </div>
        <div class="funcList">
            <a href="{% url 'common:signup' %}">JOIN US</a>
        </div>
        {% else %}
        <div class="funcList">
            <a href="{% url 'common:logout' %}">{{ user.username }} [LOGOUT]</a>
        </div>
        <div class="funcList">
            <a href="/board">Sharing List</a>
        </div>
        {% endif %}
    </div>

    <br><br><br>
    <div>
        빠르고 쉬운 차 공유 신청 !
        <br><br>
        합리적인 가격과 유연한 이용 시간 !

        <p style="margin-top:50px; font-size:10px;">&copy; 2023 외대 카풀. All rights reserved.</p>
    </div>
</body>

</html>

car_sharing/main/templates/main/posting.html
<html>

<head>
    <title>Posted Sharing</title>
    <style>
        body {
            background-color: #041C3A;
            margin-left: 200px;
            margin-top: 100px;
        }

        #cont {
            background-color:#D6B534;
            padding:20px;
            width: 80%;
            font-weight: bold;
            font-size:20px;
            height:50%;
            border-radius: 5px 30px 30px 30px;
            margin-top: 40px;
        }
        
        a {
            margin-top: 5px;
            color: #041C3A;
            background-color: #D6B534;
            height: 90%;
            border-style: solid;
            border-width: 4px;
            border-color: #041C3A;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 10px;
            border-radius: 10px 10px;
            text-decoration: none;
            font-weight: bold;
        }

        a:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            box-shadow: 0px 0px 10px #D6B534, 0 0 10px #D6B534, 0px 0px 10px  #D6B534;
        }
    </style>
</head>

<body>
    <p style="color: #D6B534; font-style:italic; font-weight:bold; font-size: 50px; margin-bottom: 10px;"> " {{post.postname}} " </p>
    
    <p id="cont">{{post.contents}}</p>
    {% if user.username == post.user.username %}
    <br><br>
    <a href="/board/{{post.pk}}/remove">Delete</a>
    {% endif %}
    <a href="/board">Go to List</a>
</body>

</html>

car_sharing/main/templates/main/remove_post.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Removing</title>
    <style>
        body {
            background-color: #041C3A;
            text-align: center;
            color: #D6B534;
        }

        form {
            height: 60%;
            margin: auto;
            border-style: solid;
            width: 50%;
            background-color: #041C3A;
            border-style: solid;
            border-width: 4px;
            border-color: #D6B534;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 50px;
            border-radius: 10px 10px;
            text-decoration: none;
            font-weight: bold;
        }

        p {
            font-style: italic;
            font-size: 100px;
            color: #D6B534;
            margin-bottom: 30px;

        }

        button {
            margin-top: 5px;
            color: #041C3A;
            background-color: #D6B534;
            height: 90%;
            border-style: solid;
            border-width: 4px;
            border-color: #041C3A;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 20px;
            border-radius: 10px 10px;
        }

        button:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            box-shadow: 0px 0px 10px #D6B534, 0 0 10px #D6B534, 0px 0px 10px #D6B534;
        }

    </style>
</head>

<body>
    <p>Delete Post</p>
    <form method="POST">
        {% csrf_token %}
        <h1> " {{ Post.postname }} " </h1>
        <button>I'm really sure to delete this post.</button>
    </form>
</body>

</html>

car_sharing/main/templates/main/writing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>New Sharing</title>
    <style>
        body {
            background-color: #041C3A;
            margin-left: 200px;
            margin-top: 100px;
            color: #D6B534;
        }

        input {
            border-radius: 10px 10px;
            padding:10px;
            margin-bottom:10px;
            width: 80%;
        }

        textarea {
            border-radius: 10px 10px;
            padding:10px;
            width: 80%;
        }

        #comp {
            margin-top: 70px;
            color: #041C3A;
            width: auto;
            background-color: #D6B534;
            height: 90%;
            border-style: solid;
            border-width: 4px;
            border-color: #041C3A;
            background-size: cover;
            text-align: center;
            font-size: 20px;
            padding: 10px;
            border-radius: 10px 10px;
        }
        
        #comp:hover {
            /* 링크에 마우스 올라가면 적용될 스타일 (네온사인 같은 그림자) */
            box-shadow: 0px 0px 10px #D6B534, 0 0 10px #D6B534, 0px 0px 10px #D6B534;
        }

    </style>
</head>

<body>
    <h1 style="font-style:italic;">Write Down Your Sharing Information</h1>
    <form method="POST">
        {% csrf_token %}
        <p style="font-size: 25px; margin-bottom: 5px;">Title</p>
        <input type="text" name="postname"><br>
        <p style="font-size: 25px; margin-bottom: 5px;">Details </p>
        <textarea rows="10" cols="50" name="contents"></textarea><br>
        <input id="comp" type="submit" value="Complete">
    </form>
</body>

</html>